WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39a8fd10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/840eb33a-c71e-4c49-aaa3-19dc209b37af/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39a8ddd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/840eb33a-c71e-4c49-aaa3-19dc209b37af/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f399732d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/840eb33a-c71e-4c49-aaa3-19dc209b37af/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39850b90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2e9e4a00-508b-4c96-83c4-a4a334c7ea24/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f398536d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2e9e4a00-508b-4c96-83c4-a4a334c7ea24/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39853150>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2e9e4a00-508b-4c96-83c4-a4a334c7ea24/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b1df90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9a46473b-7062-416c-8ffa-71aedcd83336/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b1e550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9a46473b-7062-416c-8ffa-71aedcd83336/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b1fbd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9a46473b-7062-416c-8ffa-71aedcd83336/screenshot