WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b9d7d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1373bde0-385d-4878-8ce5-636289f27341/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b9f4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1373bde0-385d-4878-8ce5-636289f27341/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3994ead0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1373bde0-385d-4878-8ce5-636289f27341/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39a8fb10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8ff670a4-37e0-4773-bde3-0adaa250bac6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39a8d510>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8ff670a4-37e0-4773-bde3-0adaa250bac6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3970ad50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8ff670a4-37e0-4773-bde3-0adaa250bac6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b6a590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b3db9c19-4d95-4beb-8504-93f2b0ba0dbd/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b6b6d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b3db9c19-4d95-4beb-8504-93f2b0ba0dbd/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b680d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b3db9c19-4d95-4beb-8504-93f2b0ba0dbd/screenshot