WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fececd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1f7f3cf1-d44e-4aa1-ac2d-35059fbb81c2/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fecc450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1f7f3cf1-d44e-4aa1-ac2d-35059fbb81c2/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fece350>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1f7f3cf1-d44e-4aa1-ac2d-35059fbb81c2/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fba1fd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a40d769f-cdb1-4ab4-9fdc-85b9d8b07c32/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fba1f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a40d769f-cdb1-4ab4-9fdc-85b9d8b07c32/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fba1a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a40d769f-cdb1-4ab4-9fdc-85b9d8b07c32/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fb26490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4041284b-a98a-4802-97d3-6d2e0821a0d3/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fb27690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4041284b-a98a-4802-97d3-6d2e0821a0d3/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fb27a50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4041284b-a98a-4802-97d3-6d2e0821a0d3/screenshot