WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395ba850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/44acdeb0-0162-4df4-96d6-32105a3d6430/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395ba710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/44acdeb0-0162-4df4-96d6-32105a3d6430/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395b8150>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/44acdeb0-0162-4df4-96d6-32105a3d6430/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52392b5350>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d26a9d5-73df-4db3-b243-361b3927511e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52392b7f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d26a9d5-73df-4db3-b243-361b3927511e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523928d9d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d26a9d5-73df-4db3-b243-361b3927511e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239648d10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a17046a4-d9a7-4092-b952-4cfd11c34f68/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239648c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a17046a4-d9a7-4092-b952-4cfd11c34f68/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239649950>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a17046a4-d9a7-4092-b952-4cfd11c34f68/screenshot