WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f399da890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/84e619dc-eba7-4d9d-90c4-d656c5617a41/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f399dab90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/84e619dc-eba7-4d9d-90c4-d656c5617a41/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f399dbc50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/84e619dc-eba7-4d9d-90c4-d656c5617a41/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3998dbd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2477a1bd-8370-4457-beaf-9e981341333d/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3998df10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2477a1bd-8370-4457-beaf-9e981341333d/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3998edd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2477a1bd-8370-4457-beaf-9e981341333d/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39c24b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2cb0dfdd-93e3-4b27-835f-52382479ac47/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39c24710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2cb0dfdd-93e3-4b27-835f-52382479ac47/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39a8f790>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2cb0dfdd-93e3-4b27-835f-52382479ac47/screenshot