WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239595250>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6013af45-d253-416c-8a0d-1536b801d43a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239595ed0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6013af45-d253-416c-8a0d-1536b801d43a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239597790>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6013af45-d253-416c-8a0d-1536b801d43a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523933e490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54c6639f-2987-4d3f-91f2-016083719bdd/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523933c0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54c6639f-2987-4d3f-91f2-016083719bdd/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523928f390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54c6639f-2987-4d3f-91f2-016083719bdd/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395f6390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a2aeb7bf-e2ff-4aec-8581-6017b1f30e6a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395f7190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a2aeb7bf-e2ff-4aec-8581-6017b1f30e6a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523968d1d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a2aeb7bf-e2ff-4aec-8581-6017b1f30e6a/screenshot