WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395eb850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c1bfa58d-8234-47db-9988-2783aa52b4a6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395e9bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c1bfa58d-8234-47db-9988-2783aa52b4a6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395eadd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c1bfa58d-8234-47db-9988-2783aa52b4a6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523919e010>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/00e14b2f-25c8-4f07-96de-1e1292fcf831/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523919fb90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/00e14b2f-25c8-4f07-96de-1e1292fcf831/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523919e910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/00e14b2f-25c8-4f07-96de-1e1292fcf831/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5238fa2750>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/80074e09-0db8-468d-a23b-134996ce95ab/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5238fa2850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/80074e09-0db8-468d-a23b-134996ce95ab/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5238fa03d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/80074e09-0db8-468d-a23b-134996ce95ab/screenshot