WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523a8138d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df34cee1-4380-406e-b321-a5d7935f6f4b/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523a811590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df34cee1-4380-406e-b321-a5d7935f6f4b/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523a7e0b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df34cee1-4380-406e-b321-a5d7935f6f4b/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523943ce10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f2b7bd0-3c9d-4fef-a445-965b65a9ab23/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523943c090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f2b7bd0-3c9d-4fef-a445-965b65a9ab23/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523943e450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f2b7bd0-3c9d-4fef-a445-965b65a9ab23/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523955b010>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a6f89689-ac98-4c89-ad89-126a38173829/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523955b8d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a6f89689-ac98-4c89-ad89-126a38173829/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239559190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a6f89689-ac98-4c89-ad89-126a38173829/screenshot