WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3ad328d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/11c0fd2a-6a31-4555-848b-60e3ebe5ef8c/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3ae93610>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/11c0fd2a-6a31-4555-848b-60e3ebe5ef8c/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3ae65510>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/11c0fd2a-6a31-4555-848b-60e3ebe5ef8c/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3994cc90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/04b0f65c-4f5d-47e5-b177-c2f4ff9c3b69/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3994cfd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/04b0f65c-4f5d-47e5-b177-c2f4ff9c3b69/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3994e3d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/04b0f65c-4f5d-47e5-b177-c2f4ff9c3b69/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39abe850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d82bf608-587f-4338-a32e-f28aaeb70f1f/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39abfb90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d82bf608-587f-4338-a32e-f28aaeb70f1f/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39abf290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d82bf608-587f-4338-a32e-f28aaeb70f1f/screenshot