WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3992db10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6d8ea121-29b4-4688-be0e-27605d19a78c/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3992dc50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6d8ea121-29b4-4688-be0e-27605d19a78c/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3992c790>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6d8ea121-29b4-4688-be0e-27605d19a78c/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39688c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/11dc1af8-6769-4663-a358-a2cab5e4079a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39689710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/11dc1af8-6769-4663-a358-a2cab5e4079a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39689590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/11dc1af8-6769-4663-a358-a2cab5e4079a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f398c6c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/92d8a5b7-2a70-40b6-a1ae-17ede3261766/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f398c7110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/92d8a5b7-2a70-40b6-a1ae-17ede3261766/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39a4c4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/92d8a5b7-2a70-40b6-a1ae-17ede3261766/screenshot