WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52393ba1d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/91d43991-4a5c-4306-93ab-2e8ccc90aa62/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52393b8ed0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/91d43991-4a5c-4306-93ab-2e8ccc90aa62/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52393b8b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/91d43991-4a5c-4306-93ab-2e8ccc90aa62/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523935c6d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c0fa9d69-3a9a-4bc4-b802-efcdd89d1da6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523935d250>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c0fa9d69-3a9a-4bc4-b802-efcdd89d1da6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523935d690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c0fa9d69-3a9a-4bc4-b802-efcdd89d1da6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52392bac50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ee3ae742-f25d-40f9-88ba-9bc266d86e59/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52392bb110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ee3ae742-f25d-40f9-88ba-9bc266d86e59/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239510d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ee3ae742-f25d-40f9-88ba-9bc266d86e59/screenshot